version: '3.8'
services:
  db:
    image: postgres
    container_name: challenge-maxxidata
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=challenge_db
      - POSTGRES_USER=cleyton
      - POSTGRES_PASSWORD=7challenge
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: