version: '3.8'
services:
  db:
    image: postgres
    container_name: challenge-maxxidata
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=maxxidata
      - POSTGRES_USER=cleyton
      - POSTGRES_PASSWORD=7maxxidata
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: